plugins {
    id 'com.android.application'
}

android {
    namespace 'com.melvin.idiotizador'
    compileSdk 34

    defaultConfig {
        applicationId 'com.melvin.idiotizador'
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            // Firmado con la clave de debug para poder instalarlo directamente
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
